### ISSUE TITLE
how do you compute ACD

### ISSUE THREAD

**Issue by jeannotes** [matheusgadelha/PointCloudLearningACD#3]
would you like to release the code about   point cloud approximate comvex decomposotion

**Comment by matheusgadelha** [comment]
We used an open source implementation of the V-HACD algorithm found here: https://github.com/kmammou/v-hacd

More details can be found in our paper.

**Comment by AruniRC** [comment]
Adding to that, @jeannotes -- we also share the pre-computed ACD results on the training datasets, which can be downloaded following the "Data Setup" instructions in our README: https://github.com/matheusgadelha/PointCloudLearningACD/blob/master/README.md#data-setup
