### ISSUE TITLE
Baseline Clustering Methods

### ISSUE THREAD

**Issue by hansen7** [matheusgadelha/PointCloudLearningACD#4]
Hi, thanks for sharing the code!

Do you have the implementations of baseline clustering methods for part segmentation tasks? 

(Shown in figure 5, methods include K-means, spectral clustering and hierarchical agglomerative clustering (HAC))

**Comment by hansen7** [comment]
I guess they are all available in `scikit-learn`?

**Comment by matheusgadelha** [comment]
Yes they are all available in `scikit-learn`. Closing this for now, feel free to reopen.
